M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Sat Oct 26 23:49:21 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-26T23:49:21+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X139.3Y-86.585
X145.08Y-86.585
M30
