M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Tue 26 Nov 2024 11:25:41 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-26T11:25:41+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X129.025Y-74.62
X134.805Y-74.62
T2
X118.0Y-50.2
X118.0Y-78.0
X165.975Y-50.2
X165.975Y-78.0
M30
